### ISSUE TITLE
Unspecified Division Issues in Python 3 Conversion

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/matter#5]
In the following places, I'm not sure whether the code is using float or floor division. Could you clarify?

*  TestLattice.py (/matter/tests/TestLattice.py): Lines 48, 50, 52
*  TestSuperCell.py (/matter/tests/TestSuperCell.py):  Lines 70-72
*  SymmetryUtilities.py (/matter/python/matter/SymmetryUtilities.py): Lines 145, 401, 413, 473, 477, 497, 729, 733
*  makeEllipsoid.py (/matter/python/matter/expansion/makeEllipsoid.py): Line 75
*  P_pdb.py (/matter/python/matter/Parsers/P_pdb.py): Lines 110, 128, 149

**Comment by yxqd** [comment]
*  TestLattice.py (/matter/tests/TestLattice.py): Lines 48, 50, 52:  *float*
*  TestSuperCell.py (/matter/tests/TestSuperCell.py):  Lines 70-72: *float*
*  SymmetryUtilities.py (/matter/python/matter/SymmetryUtilities.py): Lines 145, 401, 413, 473, 477, 497, 729, 733: *all except last two: float; last two: integer*
*  makeEllipsoid.py (/matter/python/matter/expansion/makeEllipsoid.py): Line 75: *float*
*  P_pdb.py (/matter/python/matter/Parsers/P_pdb.py): Lines 110, 128, 149: *float*
