### ISSUE TITLE
Invalid Token Error for fix_setuptools_chmod.py

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/matter#6]
In fix_setuptools_chmod.py (/matter/fix_setuptools_chmod.py), on line 52, I'm getting a SyntaxError for having an "invalid token." The code that raises this error is:
```
mode = ((os.stat(f)[stat.ST_MODE]) | 0444) & 07755
```

Are `0444` and `07755` octals? If so, the problem is that Python 3 has changed how you define them. I know how to fix this.

However, if they are not octals, do you have any idea how to fix this? I have no idea if those numbers are not octals.

**Comment by yxqd** [comment]
Yes they are octal constants
