### ISSUE TITLE
Undefined Name "np" in Site.py

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/matter#7]
On lines 12 and 26 in Site.py (/matter/python/matter/Site.py), Flake8 is saying that `np` is an undefined variable name. I'm pretty sure that `np` is supposed to be an alias for `numpy`, but I'm not sure because numpy is not imported.

Are these `np` variables supposed to refer to `numpy`?

**Comment by yxqd** [comment]
I agree.
