### ISSUE TITLE
`10^-7` in utils.py?

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/matter#8]
On line 3 in utils.py (/matter/python/matter/utils.py), there is the following code:
```
tol = 10^-7
```

As it is currently written, this line of code is performing a bitwise XOR operation on 10 and -7. Is this actually what this is supposed to do, or is it supposed to be evaluating 10 to the -7 power?

**Comment by yxqd** [comment]
Good catch! Please change it to 1e-7
