### ISSUE TITLE
Undefined Names in shapeUtils.py

### ISSUE THREAD

**Issue by ilumsden** [danse-inelastic/matter#9]
In shapeUtils.py (/matter/python/matter/expansion/shapeUtils.py), there are the following undefined names:
*  `Structure`: Lines 43 and 51
*  `makeEllipsoid`: Lines 45, 47, 49, 53, 55, and 57

What are these? Are there supposed to be imports for them?

**Comment by yxqd** [comment]
I guess you need to import them:

* Structure: https://github.com/danse-inelastic/matter/blob/4226711ce22afec0ebebe481f4f6b0c85cd341ee/python/matter/Structure.py#L12
* makeEllipsoid: https://github.com/danse-inelastic/matter/blob/4226711ce22afec0ebebe481f4f6b0c85cd341ee/python/matter/expansion/makeEllipsoid.py#L36
